export const DATA = [
    {
        id:"1",
        lastname:"Sephiroth",
        firstname:"Cloud"
    },
    {
        id:"2",
        lastname:"Master",
        firstname:"Dungeon"
    },
    {
        id:"3",
        lastname:"Mizzet",
        firstname:"Niv"
    },
    {
        id:"4",
        lastname:"Voidwalker",
        firstname:"Dauthi"
    },
    {
        id:"5",
        lastname:"Sisay",
        firstname:"Captain"
    },
    {
        id:"6",
        lastname:"Caretaker",
        firstname:"Shirei"
    },
    {
        id:"7",
        lastname:"Lord",
        firstname:"Edge"
    },
    {
        id:"8",
        lastname:"Doctor",
        firstname:"The"
    },
    {
        id:"9",
        lastname:"Ilmarinen",
        firstname:"Seppä"
    },
    {
        id:"10",
        lastname:"Väinämöinen",
        firstname:"Vakavanha"
    },
    {
        id:"11",
        lastname:"Zangetsu",
        firstname:"Tensa"
    },
    {
        id:"12",
        lastname:"Kefka",
        firstname:"Emperor"
    },
    {
        id:"13",
        lastname:"Taivaskavelija",
        firstname:"Luukas"
    },
    {
        id:"14",
        lastname:"Taivaskavelija",
        firstname:"Ana"
    },
    {
        id:"15",
        lastname:"Luukas",
        firstname:"Jorma"
    }
    
]